import { Ability } from './types';

export const ALL_ABILITIES: Ability[] = [
  // ── EMPIRE VANGUARD ──────────────────────────────────────────
  {
    id: 'iron_guard',
    name: 'Iron Guard',
    description: 'Increases RES and CON for 3 turns. Self-target.',
    type: 'Status',
    element: 'Physical',
    mpCost: 15,
    cooldown: 5,
    target: 'Self',
    magnitude: 1.5,
    statusEffects: ['iron_body_buff'], // Note: need to define these in statusEffects.ts
    requiredLevel: 1,
  },
  {
    id: 'shield_bash',
    name: 'Shield Bash',
    description: 'Deals physical damage and has a high chance to stun.',
    type: 'Physical',
    element: 'Physical',
    mpCost: 10,
    cooldown: 3,
    target: 'SingleEnemy',
    magnitude: 1.2,
    statusEffects: ['stun'],
    requiredLevel: 1,
  },
  {
    id: 'empire_decree',
    name: 'Empire\'s Decree',
    description: 'Forces all enemies to attack the user for 2 turns.',
    type: 'Status',
    element: 'Physical',
    mpCost: 20,
    cooldown: 6,
    target: 'AllEnemies',
    magnitude: 0,
    statusEffects: ['taunt'],
    requiredLevel: 5,
  },

  // ── AETHER WEAVER ─────────────────────────────────────────────
  {
    id: 'aether_pulse',
    name: 'Aether Pulse',
    description: 'A blast of pure aether energy. Hits all enemies.',
    type: 'Magical',
    element: 'Aether',
    mpCost: 25,
    cooldown: 2,
    target: 'AllEnemies',
    magnitude: 1.5,
    requiredLevel: 1,
  },
  {
    id: 'mana_shield',
    name: 'Mana Shield',
    description: 'Converts MP into a protective barrier.',
    type: 'Status',
    element: 'Aether',
    mpCost: 30,
    cooldown: 8,
    target: 'Self',
    magnitude: 2.0,
    statusEffects: ['mana_barrier'],
    requiredLevel: 1,
  },
  {
    id: 'resonance_overload',
    name: 'Resonance Overload',
    description: 'Deals massive aether damage to a single target and silences them.',
    type: 'Magical',
    element: 'Aether',
    mpCost: 40,
    cooldown: 5,
    target: 'SingleEnemy',
    magnitude: 3.0,
    statusEffects: ['silence'],
    requiredLevel: 5,
  },

  // ── SOUL REAPER ───────────────────────────────────────────────
  {
    id: 'life_siphon',
    name: 'Life Siphon',
    description: 'Deals magical damage and restores HP equal to 50% of damage dealt.',
    type: 'Magical',
    element: 'Dark',
    mpCost: 20,
    cooldown: 3,
    target: 'SingleEnemy',
    magnitude: 1.4,
    requiredLevel: 1,
  },
  {
    id: 'ghost_slash',
    name: 'Ghost Slash',
    description: 'A physical strike that ignores 50% of the enemy\'s defense.',
    type: 'Physical',
    element: 'Void',
    mpCost: 15,
    cooldown: 2,
    target: 'SingleEnemy',
    magnitude: 1.3,
    requiredLevel: 1,
  },
  {
    id: 'reaper_mark',
    name: 'Reaper\'s Mark',
    description: 'Marks an enemy. They take 25% increased damage from all sources.',
    type: 'Status',
    element: 'Dark',
    mpCost: 15,
    cooldown: 4,
    target: 'SingleEnemy',
    magnitude: 1.25,
    statusEffects: ['marked'],
    requiredLevel: 5,
  },
  // ── VOID STALKER ─────────────────────────────────────────────
  {
    id: 'stealth',
    name: 'Stealth',
    description: 'Become difficult to perceive for 3 turns. Next attack is guaranteed critical.',
    type: 'Status',
    element: 'Void',
    mpCost: 15,
    cooldown: 4,
    target: 'Self',
    magnitude: 1.0,
    statusEffects: ['hidden'],
    requiredLevel: 1,
  },
  {
    id: 'critical_strike',
    name: 'Critical Strike',
    description: 'A precise strike with increased critical damage.',
    type: 'Physical',
    element: 'Physical',
    mpCost: 10,
    cooldown: 0,
    target: 'SingleEnemy',
    magnitude: 1.5,
    requiredLevel: 1,
  },
  {
    id: 'shadow_step_ability',
    name: 'Shadow Step',
    description: 'Teleport behind an enemy and strike. Ignores defense.',
    type: 'Physical',
    element: 'Void',
    mpCost: 20,
    cooldown: 3,
    target: 'SingleEnemy',
    magnitude: 1.8,
    requiredLevel: 5,
  },

  // ── IMPERIAL INQUISITOR ───────────────────────────────────────
  {
    id: 'heresy_purge',
    name: 'Heresy Purge',
    description: 'Cleanses all buffs from an enemy and deals magical damage.',
    type: 'Magical',
    element: 'Light',
    mpCost: 20,
    cooldown: 4,
    target: 'SingleEnemy',
    magnitude: 1.6,
    requiredLevel: 1,
  },
  {
    id: 'stun_lock',
    name: 'Stun Lock',
    description: 'Strikes an enemy with divine power, silencing and stunning them.',
    type: 'Magical',
    element: 'Light',
    mpCost: 25,
    cooldown: 6,
    target: 'SingleEnemy',
    magnitude: 1.2,
    statusEffects: ['stun', 'silence'],
    requiredLevel: 1,
  },
  {
    id: 'confession_aura',
    name: 'Confession Aura',
    description: 'Reduces the INT and WIS of all enemies.',
    type: 'Status',
    element: 'Light',
    mpCost: 20,
    cooldown: 5,
    target: 'AllEnemies',
    magnitude: 0.8,
    statusEffects: ['slow'],
    requiredLevel: 5,
  },
];