import { Quest } from './types';

export const ALL_QUESTS: Quest[] = [
  // ── MAIN STORY ───────────────────────────────────────────────
  {
    id: 'q_main_01',
    title: 'Awakening in Aurum',
    type: 'main',
    description: 'You wake in the imperial capital with no memory. The emperor\'s guard is looking for you. Find out why.',
    objectives: [
      { id: 'o1', description: 'Speak to the Imperial Herald at the Citadel gate', completed: false },
      { id: 'o2', description: 'Survive the ambush in the market district', completed: false },
      { id: 'o3', description: 'Reach the Ashfields before the guard catches you', completed: false },
    ],
    rewardGold: 200, rewardExp: 500, rewardAeth: 20,
    rewardItems: ['iron_blade'],
    status: 'available', requiredLevel: 1, areaId: 'valdris_capital',
  },
  {
    id: 'q_main_02',
    title: 'What Sleeps in Keth',
    type: 'main',
    description: 'The mines of Keth have gone silent. The empire wants answers. You need what\'s inside.',
    objectives: [
      { id: 'o1', description: 'Descend into the Keth mines', completed: false },
      { id: 'o2', description: 'Find the source of the silence', completed: false },
      { id: 'o3', description: 'Retrieve the Aether Core fragment', completed: false },
    ],
    rewardGold: 400, rewardExp: 900, rewardAeth: 40,
    rewardItems: ['aether_shard', 'obsidian_shield'],
    status: 'available', requiredLevel: 3, areaId: 'valdris_ironmines',
  },
  {
    id: 'q_main_03',
    title: 'The Gate Must Not Open',
    type: 'main',
    description: 'The Rift Gate of Valdris is destabilizing. If it opens fully, the void floods the heartland.',
    objectives: [
      { id: 'o1', description: 'Reach the Rift Gate sanctum', completed: false },
      { id: 'o2', description: 'Defeat the Corrupted Warden', completed: false },
      { id: 'o3', description: 'Seal the gate using the Aether Core fragment', completed: false },
    ],
    rewardGold: 600, rewardExp: 1400, rewardAeth: 80,
    rewardItems: ['rift_gauntlet'],
    status: 'available', requiredLevel: 5, areaId: 'valdris_riftgate',
  },
  {
    id: 'q_main_04',
    title: 'The Neutral City\'s Secret',
    type: 'main',
    description: 'Duskport is hiding something. A contact promises information about your past — for a price.',
    objectives: [
      { id: 'o1', description: 'Find the contact at the Twilight Anchor', completed: false },
      { id: 'o2', description: 'Retrieve the stolen imperial manifest', completed: false },
      { id: 'o3', description: 'Decide: deliver it to the empire or burn it', completed: false },
    ],
    rewardGold: 500, rewardExp: 1100, rewardAeth: 60,
    status: 'available', requiredLevel: 6, areaId: 'nocthar_duskport',
  },
  {
    id: 'q_main_05',
    title: 'Signal from the Spire',
    type: 'main',
    description: 'The Obsidian Spire is broadcasting a signal. It contains coordinates — and your name.',
    objectives: [
      { id: 'o1', description: 'Ascend the Obsidian Spire', completed: false },
      { id: 'o2', description: 'Defeat Vex\'s guardian construct', completed: false },
      { id: 'o3', description: 'Decode the signal at the peak', completed: false },
    ],
    rewardGold: 700, rewardExp: 1600, rewardAeth: 100,
    rewardItems: ['void_compass'],
    status: 'available', requiredLevel: 8, areaId: 'nocthar_obsidian_spire',
  },
  {
    id: 'q_main_06',
    title: 'Eye of the Weapon',
    type: 'main',
    description: 'The void storm is a weapon. Someone is aiming it. You need to find the trigger.',
    objectives: [
      { id: 'o1', description: 'Reach the Heart of Nocthar', completed: false },
      { id: 'o2', description: 'Survive the Storm Titan', completed: false },
      { id: 'o3', description: 'Destroy or claim the storm generator', completed: false },
    ],
    rewardGold: 900, rewardExp: 2000, rewardAeth: 150,
    rewardItems: ['shadow_cloak'],
    status: 'available', requiredLevel: 10, areaId: 'nocthar_heart',
  },
  {
    id: 'q_main_07',
    title: 'The Archive Remembers',
    type: 'main',
    description: 'Tidehaven\'s archive contains records of someone matching your description — from 800 years ago.',
    objectives: [
      { id: 'o1', description: 'Access the restricted archive section', completed: false },
      { id: 'o2', description: 'Defeat the archive guardian', completed: false },
      { id: 'o3', description: 'Read the record of the First Ess', completed: false },
    ],
    rewardGold: 600, rewardExp: 1500, rewardAeth: 90,
    status: 'available', requiredLevel: 7, areaId: 'solmara_tidehaven',
  },
  {
    id: 'q_main_08',
    title: 'The Crystal Truth',
    type: 'main',
    description: 'The Crystal Wastes hold a memory — your memory. Crystallized in aether. You need to shatter it.',
    objectives: [
      { id: 'o1', description: 'Navigate the Crystal Wastes', completed: false },
      { id: 'o2', description: 'Find the Memory Crystal', completed: false },
      { id: 'o3', description: 'Survive what the memory shows you', completed: false },
    ],
    rewardGold: 800, rewardExp: 1800, rewardAeth: 120,
    rewardItems: ['aether_staff'],
    status: 'available', requiredLevel: 9, areaId: 'solmara_crystal_wastes',
  },
  {
    id: 'q_main_09',
    title: 'Return to Origin',
    type: 'main',
    description: 'The Origin Point. Where it all began. Where it must end. The First Smith is waiting.',
    objectives: [
      { id: 'o1', description: 'Reach the Origin Point', completed: false },
      { id: 'o2', description: 'Defeat the Origin Guardian', completed: false },
      { id: 'o3', description: 'Make the final choice: destroy the Aethrix or become it', completed: false },
    ],
    rewardGold: 2000, rewardExp: 5000, rewardAeth: 500,
    rewardItems: ['aethrix_blade', 'crown_of_tiena'],
    status: 'available', requiredLevel: 15, areaId: 'solmara_origin',
  },

  // ── SIDE QUESTS ──────────────────────────────────────────────
  {
    id: 'q_side_ashfields',
    title: 'Let Them Rest',
    type: 'side',
    description: 'The ghosts of the Ashfields cannot move on. A veteran asks you to find his brother\'s remains.',
    objectives: [
      { id: 'o1', description: 'Search the eastern Ashfields', completed: false },
      { id: 'o2', description: 'Defeat the Ash Wraith guarding the remains', completed: false },
      { id: 'o3', description: 'Return the remains to the veteran', completed: false },
    ],
    rewardGold: 300, rewardExp: 600, rewardAeth: 15,
    status: 'available', requiredLevel: 2, areaId: 'valdris_ashfields',
  },
  {
    id: 'q_side_mines',
    title: 'The Deep Thing',
    type: 'side',
    description: 'Something in the mines is not hostile. It\'s trying to communicate. Keth wants it destroyed. You\'re not sure.',
    objectives: [
      { id: 'o1', description: 'Find the Deep Thing in level 3 of the mines', completed: false },
      { id: 'o2', description: 'Attempt communication', completed: false },
    ],
    rewardGold: 250, rewardExp: 700, rewardAeth: 25,
    status: 'available', requiredLevel: 3, areaId: 'valdris_ironmines',
  },
  {
    id: 'q_side_border',
    title: 'The Deserter\'s Truth',
    type: 'side',
    description: 'An imperial deserter claims the border war is manufactured. He has proof. He needs an escort.',
    objectives: [
      { id: 'o1', description: 'Find the deserter at Fort Ironveil', completed: false },
      { id: 'o2', description: 'Escort him through the Fringe raiders', completed: false },
    ],
    rewardGold: 350, rewardExp: 800, rewardAeth: 30,
    status: 'available', requiredLevel: 4, areaId: 'valdris_border',
  },
  {
    id: 'q_side_rift',
    title: 'What Came Through',
    type: 'side',
    description: 'Something came through the Rift Gate before it was sealed. It\'s been living in the sanctum walls.',
    objectives: [
      { id: 'o1', description: 'Track the entity through the sanctum', completed: false },
      { id: 'o2', description: 'Capture or destroy it', completed: false },
    ],
    rewardGold: 400, rewardExp: 1000, rewardAeth: 45,
    rewardItems: ['void_compass'],
    status: 'available', requiredLevel: 5, areaId: 'valdris_riftgate',
  },
  {
    id: 'q_side_marsh',
    title: 'The Undying Captain',
    type: 'side',
    description: 'An imperial captain died in the Void Marsh 50 years ago. He\'s still giving orders. His troops obey.',
    objectives: [
      { id: 'o1', description: 'Find the Undying Captain\'s command post', completed: false },
      { id: 'o2', description: 'Break the void binding keeping him alive', completed: false },
    ],
    rewardGold: 300, rewardExp: 750, rewardAeth: 20,
    status: 'available', requiredLevel: 3, areaId: 'nocthar_voidmarsh',
  },
  {
    id: 'q_side_spire',
    title: 'Vex\'s Bargain',
    type: 'side',
    description: 'Vex will forge you a legendary weapon — but only if you retrieve a specific ore from the Spire\'s peak.',
    objectives: [
      { id: 'o1', description: 'Reach the Spire\'s peak', completed: false },
      { id: 'o2', description: 'Retrieve the Void-Iron ore', completed: false },
      { id: 'o3', description: 'Return to Vex', completed: false },
    ],
    rewardGold: 0, rewardExp: 1200, rewardAeth: 0,
    rewardItems: ['void_reaper'],
    status: 'available', requiredLevel: 8, areaId: 'nocthar_obsidian_spire',
  },
  {
    id: 'q_side_fringe',
    title: 'The Other Side',
    type: 'side',
    description: 'A Fringe commander wants to talk. Not fight. She says the empire started this. She has evidence.',
    objectives: [
      { id: 'o1', description: 'Infiltrate the Fringe War Camp', completed: false },
      { id: 'o2', description: 'Meet Commander Rael without triggering combat', completed: false },
      { id: 'o3', description: 'Decide: believe her or report her', completed: false },
    ],
    rewardGold: 400, rewardExp: 1000, rewardAeth: 50,
    status: 'available', requiredLevel: 6, areaId: 'nocthar_fringe_camp',
  },
  {
    id: 'q_side_storm',
    title: 'The Storm Forger\'s Price',
    type: 'side',
    description: 'The Storm Forger will craft anything — but his price is a memory. A real one. Permanently.',
    objectives: [
      { id: 'o1', description: 'Reach the Storm Forger', completed: false },
      { id: 'o2', description: 'Choose which memory to sacrifice', completed: false },
    ],
    rewardGold: 0, rewardExp: 1500, rewardAeth: 0,
    rewardItems: ['crown_of_tiena'],
    status: 'available', requiredLevel: 10, areaId: 'nocthar_heart',
  },
  {
    id: 'q_side_drowned',
    title: 'Voices from Aethos',
    type: 'side',
    description: 'Divers report hearing voices from the sunken city. The voices are speaking in a language that hasn\'t existed for 800 years.',
    objectives: [
      { id: 'o1', description: 'Dive into the Drowned City', completed: false },
      { id: 'o2', description: 'Find the source of the voices', completed: false },
    ],
    rewardGold: 350, rewardExp: 900, rewardAeth: 35,
    status: 'available', requiredLevel: 5, areaId: 'solmara_drowned_city',
  },
  {
    id: 'q_side_crystals',
    title: 'The Resonance Sickness',
    type: 'side',
    description: 'Crystal Warden soldiers are going mad from prolonged exposure. Lyra thinks she can synthesize a cure — if you gather the right crystals.',
    objectives: [
      { id: 'o1', description: 'Collect 5 Resonance Crystals from the wastes', completed: false },
      { id: 'o2', description: 'Deliver them to Lyra', completed: false },
    ],
    rewardGold: 300, rewardExp: 700, rewardAeth: 25,
    rewardItems: ['aether_shard'],
    status: 'available', requiredLevel: 7, areaId: 'solmara_crystal_wastes',
  },
  {
    id: 'q_side_vault',
    title: 'The Sealed Warning',
    type: 'side',
    description: 'The vault inscription is a warning. Someone translated it wrong — deliberately. Find who and why.',
    objectives: [
      { id: 'o1', description: 'Access the vault\'s inner sanctum', completed: false },
      { id: 'o2', description: 'Find the original translation', completed: false },
      { id: 'o3', description: 'Confront the imperial scholar responsible', completed: false },
    ],
    rewardGold: 450, rewardExp: 1100, rewardAeth: 55,
    status: 'available', requiredLevel: 8, areaId: 'solmara_vault',
  },
  {
    id: 'q_side_origin',
    title: 'The First Ess',
    type: 'side',
    description: 'The Origin Point holds a record of someone who came before you. Identical in every way. What happened to them?',
    objectives: [
      { id: 'o1', description: 'Find the First Ess\'s final log', completed: false },
      { id: 'o2', description: 'Understand what choice they made', completed: false },
    ],
    rewardGold: 500, rewardExp: 1300, rewardAeth: 70,
    status: 'available', requiredLevel: 12, areaId: 'solmara_origin',
  },

  // ── NOTICE BOARD ─────────────────────────────────────────────
  {
    id: 'q_notice_patrol',
    title: '[NOTICE] Patrol Route 7 — Overdue',
    type: 'notice',
    description: 'Imperial patrol on Route 7 has not reported in 3 days. Investigate and report. Reward upon return.',
    objectives: [
      { id: 'o1', description: 'Find the missing patrol', completed: false },
    ],
    rewardGold: 150, rewardExp: 300, rewardAeth: 8,
    status: 'available', requiredLevel: 1, areaId: 'valdris_capital',
  },
  {
    id: 'q_notice_ghost',
    title: '[NOTICE] Ghost Sightings — Ashfields East',
    type: 'notice',
    description: 'Travelers report a ghost blocking the eastern road. Clear it. 100 gold reward.',
    objectives: [
      { id: 'o1', description: 'Defeat the ghost on the eastern road', completed: false },
    ],
    rewardGold: 100, rewardExp: 200, rewardAeth: 5,
    status: 'available', requiredLevel: 2, areaId: 'valdris_ashfields',
  },
  {
    id: 'q_notice_raiders',
    title: '[NOTICE] Fringe Raiders — Border Post 12',
    type: 'notice',
    description: 'Raiders hit Border Post 12 last night. Survivors need escort to Fort Ironveil.',
    objectives: [
      { id: 'o1', description: 'Escort survivors to Fort Ironveil', completed: false },
    ],
    rewardGold: 200, rewardExp: 400, rewardAeth: 12,
    status: 'available', requiredLevel: 3, areaId: 'valdris_border',
  },
  {
    id: 'q_notice_smuggler',
    title: '[NOTICE] Wanted: The Dusk Smuggler',
    type: 'notice',
    description: 'A smuggler operating out of Duskport has stolen imperial cargo. Bring them in. Dead or alive.',
    objectives: [
      { id: 'o1', description: 'Find and confront the Dusk Smuggler', completed: false },
    ],
    rewardGold: 250, rewardExp: 500, rewardAeth: 15,
    status: 'available', requiredLevel: 4, areaId: 'nocthar_duskport',
  },
  {
    id: 'q_notice_undead',
    title: '[NOTICE] Void Marsh Undead — Bounty Active',
    type: 'notice',
    description: 'Void Revenants are crossing the marsh border. 50 gold per confirmed kill.',
    objectives: [
      { id: 'o1', description: 'Defeat 3 Void Revenants', completed: false },
    ],
    rewardGold: 150, rewardExp: 350, rewardAeth: 10,
    status: 'available', requiredLevel: 3, areaId: 'nocthar_voidmarsh',
  },
  {
    id: 'q_notice_defector',
    title: '[NOTICE] Imperial Defector — High Priority',
    type: 'notice',
    description: 'A high-ranking imperial officer has defected to the Fringe. Capture only. Information is needed.',
    objectives: [
      { id: 'o1', description: 'Locate and capture the defector', completed: false },
    ],
    rewardGold: 400, rewardExp: 700, rewardAeth: 30,
    status: 'available', requiredLevel: 6, areaId: 'nocthar_fringe_camp',
  },
  {
    id: 'q_notice_archive',
    title: '[NOTICE] Archive Theft — Tidehaven',
    type: 'notice',
    description: 'Three pre-empire relics stolen from the Tidehaven archive. Recover them. No questions asked about method.',
    objectives: [
      { id: 'o1', description: 'Recover all 3 stolen relics', completed: false },
    ],
    rewardGold: 300, rewardExp: 600, rewardAeth: 20,
    status: 'available', requiredLevel: 5, areaId: 'solmara_tidehaven',
  },
  {
    id: 'q_notice_relic',
    title: '[NOTICE] Drowned City Relic — Buyer Waiting',
    type: 'notice',
    description: 'A collector in Tidehaven wants a specific relic from the Drowned City. Dangerous dive. High reward.',
    objectives: [
      { id: 'o1', description: 'Retrieve the Aethos Sigil from the sunken palace', completed: false },
    ],
    rewardGold: 350, rewardExp: 650, rewardAeth: 25,
    status: 'available', requiredLevel: 5, areaId: 'solmara_drowned_city',
  },
  {
    id: 'q_notice_seal',
    title: '[NOTICE] Vault Seal Weakening',
    type: 'notice',
    description: 'The outer seal on the Vault of First Knowledge is cracking. Scholars need a guard while they reinforce it.',
    objectives: [
      { id: 'o1', description: 'Guard the scholars for 3 hours', completed: false },
    ],
    rewardGold: 200, rewardExp: 400, rewardAeth: 12,
    status: 'available', requiredLevel: 6, areaId: 'solmara_vault',
  },
];
