import { StatusEffect, StatusEffectType } from './types';

export const ALL_STATUS_EFFECTS: StatusEffect[] = [
  {
    id: 'poison',
    name: 'Poison',
    description: 'Deals damage over time and reduces healing received.',
    type: 'DamageOverTime',
    duration: 3,
    magnitude: 10, // 10 damage per turn
    effectIcon: 'poison_icon.png',
  },
  {
    id: 'bleed',
    name: 'Bleed',
    description: 'Deals physical damage over time.',
    type: 'DamageOverTime',
    duration: 4,
    magnitude: 15,
    effectIcon: 'bleed_icon.png',
  },
  {
    id: 'stun',
    name: 'Stun',
    description: 'Prevents character from taking action.',
    type: 'Control',
    duration: 1,
    effectIcon: 'stun_icon.png',
  },
  {
    id: 'burn',
    name: 'Burn',
    description: 'Deals fire damage over time.',
    type: 'DamageOverTime',
    duration: 2,
    magnitude: 20,
    effectIcon: 'burn_icon.png',
  },
  {
    id: 'slow',
    name: 'Slow',
    description: 'Reduces SPD and DEX.',
    type: 'Debuff',
    duration: 3,
    statModifier: { SPD: -5, DEX: -5 },
    effectIcon: 'slow_icon.png',
  },
  {
    id: 'haste',
    name: 'Haste',
    description: 'Increases SPD and DEX.',
    type: 'Buff',
    duration: 3,
    statModifier: { SPD: 5, DEX: 5 },
    effectIcon: 'haste_icon.png',
  },
  {
    id: 'iron_body_buff',
    name: 'Iron Body',
    description: 'Increases resilience and constitution.',
    type: 'Buff',
    duration: 3,
    statModifier: { RES: 10, CON: 10 },
    effectIcon: 'iron_body_icon.png',
  },
  {
    id: 'taunt',
    name: 'Taunted',
    description: 'Forced to attack the user.',
    type: 'Control',
    duration: 2,
    effectIcon: 'taunt_icon.png',
  },
  {
    id: 'mana_barrier',
    name: 'Mana Barrier',
    description: 'Reduces magical damage taken.',
    type: 'Buff',
    duration: 4,
    statModifier: { RES: 15 },
    effectIcon: 'mana_barrier_icon.png',
  },
  {
    id: 'silence',
    name: 'Silence',
    description: 'Prevents characters from using spells/abilities.',
    type: 'Control',
    duration: 2,
    effectIcon: 'silence_icon.png',
  },
  {
    id: 'marked',
    name: 'Marked',
    description: 'Increases damage taken from all sources.',
    type: 'Debuff',
    duration: 3,
    magnitude: 1.25, // 25% extra damage
    effectIcon: 'marked_icon.png',
  },
  {
    id: 'hidden',
    name: 'Hidden',
    description: 'Increases dodge chance and critical hit chance.',
    type: 'Buff',
    duration: 3,
    statModifier: { DEX: 10, LCK: 10 },
    effectIcon: 'hidden_icon.png',
  },
];