import { Continent } from './types';

export const WORLD: Continent[] = [
  {
    id: 'valdris',
    name: 'Valdris — The Iron Heartland',
    description: 'The imperial core. Fortified cities, ancient battlefields, and the seat of Tiena-Nueble power.',
    lore: 'Valdris was the first continent unified under the empire. Its iron-rich mountains forged the weapons that conquered the world. Now it groans under the weight of its own authority.',
    areas: [
      {
        id: 'valdris_capital',
        name: 'Aurum Citadel',
        description: 'The golden capital of the Tiena-Nueble. Gleaming spires hide a rotting core.',
        dangerLevel: 1,
        lore: 'Built on the bones of the old world. Every stone was laid by a conquered people.',
        safeHub: {
          name: 'The Imperial Rest',
          description: 'A fortified inn reserved for imperial soldiers and their allies.',
          services: ['inn', 'healer', 'storage', 'teleport'],
        },
        market: {
          name: 'The Golden Exchange',
          itemIds: ['health_potion', 'aether_shard', 'iron_blade', 'leather_vest', 'imperial_plate'],
        },
        blacksmith: {
          name: 'Forge-Master Aldric',
          lore: 'Aldric has served the empire for 40 years. His hands are burned. His loyalty is not.',
          isLegendary: false,
          itemIds: ['iron_blade', 'imperial_plate', 'scout_bow'],
        },
        questIds: ['q_main_01', 'q_notice_patrol'],
        enemyPool: ['imperial_deserter', 'street_thug'],
      },
      {
        id: 'valdris_ashfields',
        name: 'The Ashfields',
        description: 'A scorched battlefield from the Age 412 war. Ghosts walk here.',
        dangerLevel: 2,
        lore: 'Ten thousand soldiers died here in a single day. The ash never settled.',
        safeHub: {
          name: 'Ash Warden Post',
          description: 'A military outpost staffed by veterans who refuse to leave.',
          services: ['inn', 'healer'],
        },
        market: {
          name: 'Scavenger\'s Stall',
          itemIds: ['health_potion', 'iron_blade', 'leather_vest', 'void_compass'],
        },
        questIds: ['q_side_ashfields', 'q_notice_ghost'],
        enemyPool: ['ash_wraith', 'fallen_soldier', 'bone_crawler'],
      },
      {
        id: 'valdris_ironmines',
        name: 'The Iron Mines of Keth',
        description: 'Deep mines where something ancient was unearthed. Workers stopped returning.',
        dangerLevel: 3,
        lore: 'The empire dug too deep. What they found predates the Tiena-Nueble by millennia.',
        safeHub: {
          name: 'Miner\'s Last Light',
          description: 'A cramped shelter at the mine entrance. The candles never go out.',
          services: ['inn', 'storage'],
        },
        market: {
          name: 'Keth Supply Depot',
          itemIds: ['health_potion', 'aether_shard', 'aether_staff', 'obsidian_shield'],
        },
        blacksmith: {
          name: 'Keth the Deep-Forger',
          lore: 'Keth found something in the mines. He doesn\'t speak of it. His weapons are unlike anything above ground.',
          isLegendary: true,
          itemIds: ['aethrix_blade', 'obsidian_shield', 'rift_gauntlet', 'void_reaper'],
        },
        questIds: ['q_main_02', 'q_side_mines'],
        enemyPool: ['mine_horror', 'stone_golem', 'deep_crawler'],
      },
      {
        id: 'valdris_border',
        name: 'The Bleeding Border',
        description: 'The empire\'s eastern edge. Fringe raiders attack nightly.',
        dangerLevel: 4,
        lore: 'The border has been contested for 200 years. Neither side wins. Neither side stops.',
        safeHub: {
          name: 'Fort Ironveil',
          description: 'A crumbling fortress held by sheer stubbornness.',
          services: ['inn', 'healer', 'teleport'],
        },
        market: {
          name: 'Border Black Market',
          itemIds: ['void_elixir', 'shadow_cloak', 'rift_gauntlet', 'scout_bow'],
        },
        questIds: ['q_side_border', 'q_notice_raiders'],
        enemyPool: ['fringe_raider', 'void_touched_warrior', 'shadow_beast'],
      },
      {
        id: 'valdris_riftgate',
        name: 'The Rift Gate of Valdris',
        description: 'A massive tear in reality. The empire built a fortress around it. The fortress is now empty.',
        dangerLevel: 5,
        lore: 'The first rift opened here in Age 890. The Aethrix token was discovered in its depths.',
        safeHub: {
          name: 'Rift Warden Sanctum',
          description: 'The last Rift Wardens hold this position. They are running out of time.',
          services: ['healer', 'storage'],
        },
        market: {
          name: 'Sanctum Armory',
          itemIds: ['void_elixir', 'aether_shard', 'rift_gauntlet', 'void_compass'],
        },
        blacksmith: {
          name: 'The Nameless Smith',
          lore: 'No one knows who forged the weapons here. They appear each morning. The smith is never seen.',
          isLegendary: true,
          itemIds: ['aethrix_blade', 'rift_mantle', 'crown_of_tiena', 'void_reaper'],
        },
        questIds: ['q_main_03', 'q_side_rift'],
        enemyPool: ['rift_abomination', 'void_titan', 'corrupted_warden'],
      },
    ],
  },

  {
    id: 'nocthar',
    name: 'Nocthar — The Shadow Continent',
    description: 'A continent of perpetual twilight. The Fringe has deep roots here. Ancient and dangerous.',
    lore: 'Nocthar was never fully conquered. The empire tried three times. Three times it was repelled. Now they pretend it doesn\'t exist.',
    areas: [
      {
        id: 'nocthar_duskport',
        name: 'Duskport',
        description: 'The only city in Nocthar that trades with the empire. Barely.',
        dangerLevel: 2,
        lore: 'Duskport exists because both sides need it. Neutral ground enforced by mutual fear.',
        safeHub: {
          name: 'The Twilight Anchor',
          description: 'A neutral inn. No questions asked. No weapons drawn inside.',
          services: ['inn', 'healer', 'storage', 'teleport'],
        },
        market: {
          name: 'The Shadow Bazaar',
          itemIds: ['health_potion', 'aether_shard', 'shadow_cloak', 'scout_bow', 'void_compass'],
        },
        questIds: ['q_main_04', 'q_notice_smuggler'],
        enemyPool: ['dusk_thief', 'shadow_hound'],
      },
      {
        id: 'nocthar_voidmarsh',
        name: 'The Void Marsh',
        description: 'A swamp saturated with void energy. Things that die here don\'t stay dead.',
        dangerLevel: 3,
        lore: 'The marsh was created when a rift collapsed inward. The void leaked into the water table.',
        safeHub: {
          name: 'Marsh Lantern Post',
          description: 'A raised platform above the marsh. The lanterns burn void-fire — they never go out.',
          services: ['inn', 'healer'],
        },
        market: {
          name: 'Swamp Trader\'s Cache',
          itemIds: ['health_potion', 'void_elixir', 'aether_staff', 'leather_vest'],
        },
        questIds: ['q_side_marsh', 'q_notice_undead'],
        enemyPool: ['void_revenant', 'marsh_horror', 'drowned_soldier'],
      },
      {
        id: 'nocthar_obsidian_spire',
        name: 'The Obsidian Spire',
        description: 'A tower of black glass that predates recorded history. Something broadcasts from its peak.',
        dangerLevel: 4,
        lore: 'The signal from the Spire has been detected by every empire since the first age. No one has reached the top and returned.',
        safeHub: {
          name: 'Spire Base Camp',
          description: 'Carved into the rock at the tower\'s base. Barely safe.',
          services: ['healer', 'storage'],
        },
        market: {
          name: 'Spire Scavengers',
          itemIds: ['aether_shard', 'void_compass', 'obsidian_shield', 'shadow_cloak'],
        },
        blacksmith: {
          name: 'Vex the Obsidian-Touched',
          lore: 'Vex climbed the Spire once. She came back changed. Her forge burns black. Her weapons are terrifying.',
          isLegendary: true,
          itemIds: ['void_reaper', 'rift_mantle', 'obsidian_shield', 'aethrix_blade'],
        },
        questIds: ['q_main_05', 'q_side_spire'],
        enemyPool: ['spire_guardian', 'obsidian_golem', 'signal_horror'],
      },
      {
        id: 'nocthar_fringe_camp',
        name: 'The Fringe War Camp',
        description: 'The main staging ground for Fringe forces. Entering is suicide. Or an opportunity.',
        dangerLevel: 4,
        lore: 'The Fringe is not a single faction. It is a coalition of everything the empire rejected. They are unified only by hatred.',
        safeHub: {
          name: 'Defector\'s Den',
          description: 'A hidden shelter used by imperial defectors and Fringe deserters alike.',
          services: ['inn', 'healer'],
        },
        market: {
          name: 'Fringe Armory',
          itemIds: ['rift_gauntlet', 'shadow_cloak', 'void_elixir', 'scout_bow'],
        },
        questIds: ['q_side_fringe', 'q_notice_defector'],
        enemyPool: ['fringe_champion', 'void_touched_warrior', 'beast_rider'],
      },
      {
        id: 'nocthar_heart',
        name: 'The Heart of Nocthar',
        description: 'The absolute center of the continent. A void storm has raged here for 400 years without stopping.',
        dangerLevel: 5,
        lore: 'The storm is not natural. Something is generating it. The empire\'s best scholars agree: it is a weapon.',
        safeHub: {
          name: 'Eye of the Storm Shelter',
          description: 'Impossibly, the very center of the storm is calm. A small shelter exists there.',
          services: ['healer', 'teleport'],
        },
        market: {
          name: 'Storm Salvage',
          itemIds: ['void_elixir', 'aether_shard', 'void_compass', 'rift_gauntlet'],
        },
        blacksmith: {
          name: 'The Storm Forger',
          lore: 'Lightning is his hammer. The void storm is his furnace. He has been forging for 400 years.',
          isLegendary: true,
          itemIds: ['crown_of_tiena', 'aethrix_blade', 'rift_mantle', 'void_reaper'],
        },
        questIds: ['q_main_06', 'q_side_storm'],
        enemyPool: ['storm_titan', 'void_leviathan', 'corrupted_aetherial'],
      },
    ],
  },

  {
    id: 'solmara',
    name: 'Solmara — The Sunken Archive',
    description: 'A continent of ancient ruins half-submerged in a luminescent sea. Knowledge and death in equal measure.',
    lore: 'Solmara was the seat of the civilization that preceded the empire. They discovered the Aethrix. They were destroyed by it. Their ruins hold the answers — and the warnings.',
    areas: [
      {
        id: 'solmara_tidehaven',
        name: 'Tidehaven',
        description: 'A port city built on the ruins of an ancient archive. Scholars and pirates share the docks.',
        dangerLevel: 1,
        lore: 'Every building in Tidehaven is built on something older. Dig anywhere and you find history.',
        safeHub: {
          name: 'The Scholar\'s Berth',
          description: 'A clean, well-lit inn favored by researchers and treasure hunters.',
          services: ['inn', 'healer', 'storage', 'teleport'],
        },
        market: {
          name: 'Archive Market',
          itemIds: ['health_potion', 'aether_shard', 'aether_staff', 'void_compass', 'leather_vest'],
        },
        questIds: ['q_main_07', 'q_notice_archive'],
        enemyPool: ['archive_guardian', 'rogue_scholar'],
      },
      {
        id: 'solmara_drowned_city',
        name: 'The Drowned City of Aethos',
        description: 'The original capital of the pre-empire civilization. Now 30 feet underwater.',
        dangerLevel: 3,
        lore: 'Aethos was not destroyed by war. It sank in a single night. No one survived to explain why.',
        safeHub: {
          name: 'Diver\'s Platform',
          description: 'A floating platform above the sunken city. Divers come up changed.',
          services: ['inn', 'healer'],
        },
        market: {
          name: 'Salvage Exchange',
          itemIds: ['void_compass', 'aether_shard', 'obsidian_shield', 'shadow_cloak'],
        },
        questIds: ['q_side_drowned', 'q_notice_relic'],
        enemyPool: ['drowned_guardian', 'sea_horror', 'ancient_construct'],
      },
      {
        id: 'solmara_crystal_wastes',
        name: 'The Crystal Wastes',
        description: 'A desert of shattered aether crystals. Beautiful. Lethal. Humming with power.',
        dangerLevel: 3,
        lore: 'The crystals are the remains of a catastrophic aether overload. They still radiate. Prolonged exposure causes visions.',
        safeHub: {
          name: 'Crystal Warden Station',
          description: 'A shielded outpost. The wardens wear lead-lined armor.',
          services: ['inn', 'storage'],
        },
        market: {
          name: 'Crystal Trader',
          itemIds: ['aether_shard', 'aether_staff', 'void_elixir', 'rift_gauntlet'],
        },
        blacksmith: {
          name: 'Lyra the Crystal-Weaver',
          lore: 'Lyra weaves aether crystals directly into metal. The process is agonizing. The results are extraordinary.',
          isLegendary: true,
          itemIds: ['aethrix_blade', 'rift_mantle', 'crown_of_tiena', 'obsidian_shield'],
        },
        questIds: ['q_main_08', 'q_side_crystals'],
        enemyPool: ['crystal_elemental', 'aether_wraith', 'refracted_horror'],
      },
      {
        id: 'solmara_vault',
        name: 'The Vault of First Knowledge',
        description: 'The most complete pre-empire archive ever found. Sealed for 800 years.',
        dangerLevel: 4,
        lore: 'The vault was sealed by its own creators. The inscription reads: "What is inside must never leave. What is outside must never enter."',
        safeHub: {
          name: 'Vault Antechamber',
          description: 'The outer chamber of the vault. Safe, but the walls whisper.',
          services: ['healer', 'storage'],
        },
        market: {
          name: 'Vault Contraband',
          itemIds: ['void_elixir', 'void_compass', 'aether_staff', 'shadow_cloak'],
        },
        questIds: ['q_side_vault', 'q_notice_seal'],
        enemyPool: ['vault_sentinel', 'knowledge_horror', 'ancient_warden'],
      },
      {
        id: 'solmara_origin',
        name: 'The Origin Point',
        description: 'Where the first AETH token was created. The ground still glows. Time moves differently here.',
        dangerLevel: 5,
        lore: 'The Origin Point is where the pre-empire civilization first harnessed the Aethrix. The power destroyed them. The power remains.',
        safeHub: {
          name: 'Temporal Anchor',
          description: 'A structure that exists slightly outside of time. Safe, but disorienting.',
          services: ['healer', 'teleport'],
        },
        market: {
          name: 'Origin Relics',
          itemIds: ['void_elixir', 'aether_shard', 'void_compass', 'rift_gauntlet'],
        },
        blacksmith: {
          name: 'The First Smith',
          lore: 'An ancient being who has been forging since before the empire. They claim to have made the first AETH token. They are not lying.',
          isLegendary: true,
          itemIds: ['aethrix_blade', 'crown_of_tiena', 'void_reaper', 'rift_mantle'],
        },
        questIds: ['q_main_09', 'q_side_origin'],
        enemyPool: ['origin_guardian', 'time_fractured', 'aethrix_construct'],
      },
    ],
  },
];
